input {
  beats {
    port => 5044
  }
  http {
    port  => 8080
    codec => "json"
  }
}

filter {
  ### ==== 1. Zeek ====
  if [event][module] == "zeek" {
    mutate {
      add_field => { "log_type" => "zeek" }
    }
  }
  
  ### ==== 2. Suricata ====
  else if [event][module] == "suricata" {
    mutate {
      add_field => { "log_type" => "suricata" }
    }
  }

  ### ==== 3. Wazuh ====
  else if [event][module] == "wazuh" {
    json {
      source => "message"
      target => "[wazuh]"
    }
    if "_jsonparsefailure" not in [tags] {
      mutate { remove_field => ["message"] }
    }
    date {
      match => ["[wazuh][timestamp]", "ISO8601"]
      timezone => "Asia/Ho_Chi_Minh"
      target => "@timestamp"
    }
    ruby {
      code => '
        wazuh = event.get("wazuh")
        if wazuh.is_a?(Hash)
          wazuh.each { |k, v| event.set(k, v) }
          event.remove("wazuh")
        end
      '
    }
    mutate { add_field => { "log_type" => "wazuh" } }
  }

  ### ==== 4. MultiChain ====
  else if [stream] {    
    if [stream] == "zeek" {
      mutate {
        add_field => { "log_type" => "zeek_chain" }
      }
      date {
        match        => ["ts", "YYYY-MM-dd HH:mm:ss"]
        timezone     => "Asia/Ho_Chi_Minh"
        target       => "@timestamp"
        remove_field => ["ts"]
      }
    }

    if [stream] == "suricata" {
      mutate {
        add_field => { "log_type" => "suricata_chain" }
      }
      date {
        match        => ["ts", "ISO8601"]
        timezone     => "Asia/Ho_Chi_Minh"
        target       => "@timestamp"
        remove_field => ["ts"]
      }
    }
  }

  ruby {
    code => "
      event.set('[@metadata][local_date]', event.get('@timestamp').time.localtime('+07:00').strftime('%Y.%m.%d'))
    "
  }
}

output {
  elasticsearch {
    hosts => ["https://192.168.63.148:9200"]
    index => "filebeat-%{log_type}-%{[@metadata][local_date]}"
    user => "elastic"
    password => "fCAhcngQzYzTp75FrBoj"
    ssl_enabled => true
    ssl_verification_mode => "none"
  }
  stdout {
    codec => rubydebug
  }
}
